# Generated by Django 5.1.6 on 2025-02-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuamkulimaApp', '0007_consultationrequest_trainingsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
