# Generated by Django 5.1.6 on 2025-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuamkulimaApp', '0012_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('loan_type', models.CharField(choices=[('short-term', 'Short-Term Loan'), ('long-term', 'Long-Term Loan'), ('seasonal', 'Seasonal Loan')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('farm_address', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
